image: docker:latest

services:
  - docker:dind

variables:
  UUID: 1000
  GGID: 1000
  USER: torrent

before_script:
  - 'which ssh-agent || ( apk update && apk add openssh-client )'
  - 'which git || ( apk update && apk add git )'
  - 'which rsync || ( apk update && apk add rsync )'
  - eval $(ssh-agent -s)
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - export IMAGE_TAG=$CI_REGISTRY_IMAGE:release-$CI_COMMIT_REF_NAME
  - export LATEST_IMAGE_TAG=$CI_REGISTRY_IMAGE:release-latest
  - git clone git@gitlab.deuxmax.fr:torrent/rtorrent-deamon.git ./project
  - cd ./project && git checkout $CI_COMMIT_REF_NAME

stages:
  - build

build:
  stage: build
  script:
    - docker build --build-arg UUID=$UUID --build-arg GGID=$GGID --build-arg USER=$USER -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - docker tag $IMAGE_TAG $LATEST_IMAGE_TAG
    - docker push $LATEST_IMAGE_TAG
